version: "3"
services:
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/tarslib/medusajs-backend:lastest
    container_name: medusa-server
    ports:
      - "7001:7001"
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    volumes:
      - /data/docker/medusa/backend/develop.sh:/app/medusa/develop.sh
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://cache
      NODE_ENV: development
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      API_URL: http://192.168.10.208:9000
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://192.168.10.208:9000
      MEDUSA_BACKEND_URL: http://192.168.10.208:9000
      NEXT_PUBLIC_BASE_URL: http://192.168.10.208:8000
      ADMIN_CORS: http://192.168.10.208:7000,http://192.168.10.208:7001
      STORE_CORS: http://192.168.10.208:8000
      PORT: 9000

  storefront:
    ports:
      - "8000:8000"
    image: registry.cn-hangzhou.aliyuncs.com/tarslib/medusa-front:lastest
    container_name: medusa-storefront
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://192.168.10.208:9000
      MEDUSA_BACKEND_URL: http://192.168.10.208:9000
      NEXT_PUBLIC_BASE_URL: http://192.168.10.208:8000

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
      ALLOW_IP_RANGE: 0.0.0.0/0

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379


